name: TheDrone CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'adopt'
        cache: maven
#

    - name: Build
      run: mvn --batch-mode -DskipTests package

    - name: Test
      run: mvn --batch-mode -Dmaven.test.failure.ignore=true test


